# Generated by Django 5.1.7 on 2025-03-23 20:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='unknown', max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(default='unknown', max_length=100)),
                ('nationality', models.CharField(default='unknown', max_length=100)),
                ('passport_number', models.CharField(default='unknown', max_length=100)),
                ('phone_code', models.CharField(default='unknown', max_length=10)),
                ('phone_number', models.CharField(default='unknown', max_length=20)),
                ('check_in_date', models.DateField(default='2025-01-01')),
                ('check_out_date', models.DateField(default='2025-01-01')),
                ('traveling_from', models.CharField(default='unknown', max_length=100)),
                ('hotel', models.CharField(default='Not Provided', max_length=100)),
                ('number_of_rooms', models.PositiveIntegerField(default=0)),
                ('transportation_mode', models.CharField(default='Not Provided', max_length=50)),
                ('flight_class', models.CharField(blank=True, max_length=50, null=True)),
                ('adults', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('students', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('seniors', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('youths', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('children', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('toddlers', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('infants', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(default='Not Provided', max_length=100)),
                ('payment_method', models.CharField(default='not provided', max_length=50)),
                ('visa_number', models.CharField(blank=True, max_length=100, null=True)),
                ('visa_expiry', models.CharField(blank=True, max_length=10, null=True)),
                ('visa_cvv', models.CharField(blank=True, max_length=5, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('crypto_wallet', models.CharField(blank=True, max_length=100, null=True)),
                ('creditcard_number', models.CharField(blank=True, max_length=100, null=True)),
                ('creditcard_expiry', models.CharField(blank=True, max_length=10, null=True)),
                ('creditcard_cvv', models.CharField(blank=True, max_length=5, null=True)),
                ('wise_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mpesa_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
