# Generated by Django 5.1.7 on 2025-03-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='emergency_contact',
            field=models.CharField(blank=True, default='Not Provided', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, default='not provided', max_length=50, null=True),
        ),
    ]
